apiVersion: v1
data:
  COOKIE_DOMAIN: .dev.lan
  PRODUCTION: "true"
  KUBE_URL: "__KURL__"
  KUBE_TOKEN: "__KTOKEN__"
kind: ConfigMap
metadata:
  labels:
    io.portainer.kubernetes.configuration.owner: admin
  name: serv-type-3
  namespace: default
