version: "3.3"
services:
  builder:
    container_name: builder
    image: upachko/site_builder_builder:latest
    restart: always
    environment:
      SITE_ID: 1
      API_HOST_NAME: http://api.dev.lan:3001/
      APP_PATH: /var/www/
      WWW_PATH: /var/www/html
      API_PASS: root
      API_LOGIN: root
      AUTH_KEY: 8fea39d82cfaae83ed954e7f8e821a3c981c6e854ad2155fc2a86f7d01a8fa52
      RABBIT_USER: root:JSfhkgs78yadkH
      RABBIT_HOST: 192.168.100.136
    ports:
      - "8080:80"
      - "24:22"