version: "3.3"
services:
  builder:
    container_name: builder
    image: upachko/site_builder_builder:latest
    restart: always
    environment:
      SITE_ID: 1
      API_HOST_NAME: http://api.build.lan:3001/
      APP_PATH: /var/www/
      WWW_PATH: /var/www/html
      API_PASS: root
      API_LOGIN: root
      AUTH_KEY: 8fea39d82cfaae83ed954e7f8e821a3c981c6e854ad2155fc2a86f7d01a8fa52
      RABBIT_USER: root:JSfhkgs78yadkH
      RABBIT_HOST: http://rabbit.build.lan/
    ports:
      - "8080:80"
      - "24:22"
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6479:6379"
    volumes:
      - "/var/lib/redis:/data"
  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: JSfhkgs78yadkH
    volumes:
      - "/var/lib/rabbitmqDocker:/var/lib/rabbitmq"
    ports:
      - "5671-5672:5671-5672"
      - "15672:15672"
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "30306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=hkjh7483hjkHDj
      - MYSQL_DATABASE=sitebuilder
      - MYSQL_USER=sitebuilder
      - MYSQL_PASSWORD=83hjhk3hjjh74kHDj
    volumes:
      - "/var/lib/mysqlMariaDocker:/var/lib/mysql"