version: "3.3"
services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "********:6379"
    volumes:
      - "/var/lib/sitebuilder/redis:/data"
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.7.25-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: JSfhkgs78yadkH
    volumes:
      - "/var/lib/sitebuilder/rabbitmq:/var/lib/rabbitmq"
    ports:
      - "********:5671-5672"
      - "********:15672"
  mariadbuilder:
    container_name: mariadbuilder
    image: arm64v8/mariadb
    restart: always
    ports:
      - "********:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=srkhgaorhbtj|E
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=PYSBHLrJZusKI
    volumes:
      - "/var/lib/sitebuilder/mariadb:/var/lib/mysql"
networks:
  default:
    external:
      name: sitrbuilder
