cd configs && sh init.sh && cd ../
cd mariadb && sh init.sh && cd ../
cd rabbit && sh init.sh && cd ../
cd redis && sh init.sh && cd ../
cd wsswever && sh init.sh && cd ../
cd api && sh init.sh && cd ../
cd processor && sh init.sh && cd ../
cd builder && sh init.sh && cd ../
cd front && sh init.sh && cd ../
