apiVersion: v1
kind: Service
metadata:
  name: site-processor
  namespace: default
  labels:
    app: site-processor
spec:
  ports:
    - port: 3001
  clusterIP: None
  selector:
    app: site-processor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-processor
  namespace: default
spec:
  selector:
    matchLabels:
      app: site-processor
  replicas: 1
  strategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: site-processor
        commitHash: ffff
    spec:
      containers:
        - image: upachko/site_builder_processor:latest
          imagePullPolicy: Always
          name: site-processor
          env:
            - name: PRODUCTION
              valueFrom:
                configMapKeyRef:
                  name: server-type
                  key: PRODUCTION
            - name: COOKIE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: server-type
                  key: COOKIE_DOMAIN
            #main
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: processor-default
                  key: PORT
            #rabbit
            - name: RABBIT_USER
              valueFrom:
                configMapKeyRef:
                  name: processor-default
                  key: RABBIT_USER
            - name: RABBIT_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbit-default
                  key: HOST
            #kuber
            - name: KUBE_URL
              valueFrom:
                configMapKeyRef:
                  name: server-type
                  key: KUBE_URL
            - name: KUBE_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: server-type
                  key: KUBE_TOKEN
            #wss
            - name: WEBSOCKET_HOST
              valueFrom:
                configMapKeyRef:
                  name: wsserver-default
                  key: HOST
          ports:
            - containerPort: 3001
              name: http
          lifecycle:
            postStart:
              exec:
                command: ["sh", "/var/SiteBuilderProcessor/startProcess.sh", "app"]
